# Generated by Django 4.0.6 on 2023-02-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
