# Generated by Django 4.0.6 on 2023-02-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_data', '0002_alter_notice_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
