# Generated by Django 4.0.6 on 2023-02-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_data', '0003_alter_notice_saved_at_alter_notice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
